name: typescript-nodejs-template
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/typescript-nodejs-template
  name: typescript-nodejs-template
